### PR TITLE
Replace usage of Site URL with relative URLs

### LINKED ISSUE #20: Replace usage of Site URL with relative URLs
#### Summary

When `/giphy (search)` is run and there is no `Site URL` set in the server settings, the request has a nil pointer exception, and responds back with
> Command with a trigger of '/giphy' not found. Click here to send as a message.

The server should instead use relative URLs so there is no error.

### PR DESCRIPTION
**Pull request by ivanvc**
Hi,

I was trying out this plugin and it was giving me an error and eventually gave up. Today I found #20, and after a quick change to the code made it work.

I also ran go fmt on server/plugin.go as it was giving me an error when compiling.

This PR fixes #20

### CODE REVIEW

**Comment by ivanvc** [comment]
btw, I had the same issues as the CI locally when running Go 1.13. It needs to be set to 1.12 rather than 1.13.

**Review by hanzei — APPROVED** [review]
I will fix the build error in a different PR

**Review by levb — APPROVED** [review]
Thanks for fixing this!

**Comment by levb** [comment]
Will need to wait until https://github.com/mattermost/mattermost-plugin-giphy/pull/22 is merged - the build is failing for unrelated reasons (go 1.13)

**Comment by levb** [comment]
@ivanvc Can you please sync & merge with `master` to fix the build issues?

**Comment by ivanvc** [comment]
@levb done!

**Review by DHaussermann — APPROVED** [review]
Tested and passed. 
- Giphhy plugin works when no site URL is set
- No issues found in regression testing 
- Added release testing to cover this site URL case

LGTM!

**Comment by levb** [comment]
@ivanvc Thanks for the contribution! Please join us on https://community.mattermost.com/ if you have not already, and check out other open Help Wanted issues in https://github.com/mattermost/mattermost-server/issues and plugins https://github.com/mattermost/mattermost-server/issues/12656.

**Pull request merged**
