### PR TITLE
config-weirdness

### PR DESCRIPTION
**Pull request by dnguy078**

### CODE REVIEW

**Comment by aaronrothschild** [comment]
@dnguy078 Question: Will this now show up in the system console "settings page" for this plugin?

What will the descriptive text that describes this setting read?  I suggest we add some context so they understand what the "weirdness" factor does.   

In their API docs this is how they describe it:  "Value from 0-10 which makes results weirder as you go up the scale." 

This is from a blog post: "A weirdness parameter can be passed to the Giphy endpoint. It determines how weird (or random) the GIFs we return will be."

Perhaps we can add this text that explains it a bit better:
"Set a Value from 0-10 which makes results weirder as you go up the scale. The value determines how "weird" (or random) the GIF suggestions that Giphy will return to an end-user."

**Review by levb — CHANGES_REQUESTED** [review]
@dnguy078, thanks for the contribution! You should add the new setting to `plugin.json`, see https://github.com/mattermost/mattermost-plugin-giphy/blob/master/plugin.json#L16

**Comment by dnguy078** [comment]
@levb @aaronrothschild i updated the docs for the weirdness configs.

**Review by levb — APPROVED** [review]

**Comment by mickmister** [comment]
We discussed possibly allowing the user to set the weirdness per request as well, but that is out of scope because it would require param parsing in the command.

**Review by mickmister — APPROVED** [review]
LGTM @dnguy078 thank you!

**Comment by aaronrothschild** [comment]
LGTM, Thanks @dnguy078 !

**Review by aaronrothschild — APPROVED** [review]
@levb Sorry, not on the repo, so can't remove PM-Review label.

**Pull request merged**
